project:
  type: website
  output-dir: docs

website:
  title: "lewis-r-white.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Posts.qmd
        text: Blog Posts
      - href: lewis_white_resume.pdf
        text: Resume

format:
  html:
    theme:
      - mystyles.scss
    mainfont: Montserrat
      #light: minty
      #dark: slate
    #css: styles.css
    toc: true

editor: visual

